import = [ "~/.config/alacritty/themes/flexoki_light.toml" ]

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/zsh"
args = [ "--login" ]

[window]
dynamic_padding = true

  [window.padding]
  x = 50
  y = 40

[font]
# # CommitMono + DankMono
# size = 15
# offset.x = 0
# offset.y = 0
#
#   [font.normal]
#   family = "CommitMono Nerd Font Mono"
#   style = "Regular"
#
#   [font.bold]
#   family = "CommitMono Nerd Font Mono"
#   style = "Bold"
#
#   [font.italic]
#   family = "DankMono Nerd Font"
#   style = "Italic"
#
#   [font.bold_italic]
#   family = "DankMono Nerd Font"
#   style = "Italic"

# ------

# # Maple Mono + VictorMono
# size = 15
# offset.x = 0
# offset.y = 10
#
#   [font.normal]
#   family = "Maple Mono NF"
#   style = "Light"
#
#   [font.bold]
#   family = "Maple Mono NF"
#   style = "Regular"
#
#   [font.italic]
#   family = "VictorMono Nerd Font"
#   style = "Italic"
#
#   [font.bold_italic]
#   family = "VictorMono Nerd Font"
#   style = "Bold Italic"

# ------

# JetBrainsMono + VictorMono
size = 14
offset.x = 0
offset.y = 7

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "ExtraLight"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.italic]
  family = "VictorMono Nerd Font"
  style = "Italic"

  [font.bold_italic]
  family = "VictorMono Nerd Font"
  style = "Bold Italic"

# ------

# # IBM Plex Mono
# size = 15
# offset.x = 0
# offset.y = 10
#
#   [font.normal]
#   family = "BlexMono Nerd Font Propo"
#   style = "Regular"
#
#   [font.bold]
#   family = "BlexMono Nerd Font Propo"
#   style = "Bold"
#
#   [font.italic]
#   family = "BlexMono Nerd Font Propo"
#   style = "Italic"
#
#   [font.bold_italic]
#   family = "BlexMono Nerd Font Propo"
#   style = "Bold Italic"

# ------

# # Julia Mono
# size = 15
# offset.x = 1
# offset.y = 3
#
#   [font.normal]
#   family = "JuliaMono Nerd Font Mono"
#   style = "Light"
#
#   [font.bold]
#   family = "JuliaMono Nerd Font Mono"
#   style = "SemiBold"
#
#   [font.italic]
#   family = "JuliaMono Nerd Font Mono"
#   style = "Light Italic"
#
#   [font.bold_italic]
#   family = "JuliaMono Nerd Font Mono"
#   style = "SemiBold Italic"

# ------

# # Maple Mono NF
# size = 15
# offset.x = 1
# offset.y = 10
#
#   [font.normal]
#   family = "Maple Mono NF"
#   style = "Light"
#
#   [font.bold]
#   family = "Maple Mono NF"
#   style = "Bold"
#
#   [font.italic]
#   family = "Maple Mono NF"
#   style = "LightItalic"
#
#   [font.bold_italic]
#   family = "Maple Mono NF"
#   style = "BoldItalic"

# ------

# # VictorMono
# size = 16
# offset.x = 0
# offset.y = 5
#
#   [font.normal]
#   family = "VictorMono Nerd Font"
#   style = "Regular"
#
#   [font.bold]
#   family = "VictorMono Nerd Font"
#   style = "Bold"
#
#   [font.italic]
#   family = "VictorMono Nerd Font"
#   style = "Italic"
#
#   [font.bold_italic]
#   family = "VictorMono Nerd Font"
#   style = "Bold Italic"
