#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# focus window after active space changes ---
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes ---
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# un-fullscreen on focus change
# yabai -m signal --add event=window_focused action="yabai -m query --windows --window recent | jq -e '.\"has-fullscreen-zoom\"' && yabai -m window recent --toggle zoom-fullscreen"

# focusing the window under the mouse when a window is closed ---
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# fix fullscreen issues on apps with tabs
yabai -m signal --add app='^Finder$' event=window_created action='yabai -m space --focus next; sleep 0.01; yabai -m space --focus prev'
yabai -m signal --add app='^Finder$' event=window_destroyed action='yabai -m space --focus next; sleep 0.01; yabai -m space --focus prev'
yabai -m signal --add app='^Postico 2$' event=window_created action='yabai -m space --focus next; sleep 0.01; yabai -m space --focus prev'
yabai -m signal --add app='^Postico 2$' event=window_destroyed action='yabai -m space --focus next; sleep 0.01; yabai -m space --focus prev'


# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                float          \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   12             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# To disable yabai on certain apps
# yabai -m rule --add app="ˆCalculator$" manage=off

echo "yabai configuration loaded.."

# Load JankyBorders alongside yabai
janky_borders_options=(
	style=round
	width=7.0
	hidpi=off
  # active_color=0xffdcdeaf -- For gruvbox
  # active_color=0xff56d456 -- for eva01
  # active_color=0xff629f81 -- green for light themes
  active_color=0xfff2d5cf
	inactive_color=0x00000000
)

borders "${janky_borders_options[@]}"

echo "JankyBorders loaded.."
